image: node:18.15.0 # change to match your project's node version

cache:
  paths:
    - node_modules/

before_script:
  - rm -rf build
  - CI=false npm install

build-pages:
  stage: build
  script:
    - rm -rf build
    - CI=false npm install
    - CI=false npm run build
    - rm -rf public
    - cp build/index.html build/404.html
    - mv build public
  artifacts:
    paths:
      - public
  # only:
  #   - master

pages:
  stage: deploy
  script:
    - ls

  artifacts:
    paths:
      - public
  # only:
  #   - master